export const data = [
    {
    "id":"1",
    "name": "CLI Vending machine",
    "description":"This is a simple command line vending machine built in year 2 of University. The brief was to design a working vending machine for users to interact with. There was 5 main requirements to this project. 1. View the list of products (each product must have a name & price). 2. View the amount of credit the user has. 3. Add credit. 4. Purchase a product. 5. Ask for a refund of their credit. in addition to these 5 requirements i also added in a add more money feature. This gives the uiser the option to add more credit to their balance if they dont have enough to make a purchase.",
    "imageUrl":"https://i.ibb.co/56z48ZW/Screenshot-2022-05-12-at-5-57-48-am.png",
    "gitHubLink": "https://github.com/SteColeman/CIS2152-Vending-Machine",
    "techUsed": "Javascript, Node.js",
    },
    {
    "id":"2",
    "name": "Discord NFT Bot",
    "description":"A Discord bot build using Discord.js that has a pre defined OpenSea API URL to ping with a user entered number. the bot returns the full trait list of the NFT number entered.",
    "imageUrl":"https://i.ibb.co/BfGMPCJ/Screenshot-2022-05-12-at-5-04-22-am.png",
    "gitHubLink": "https://github.com/SteColeman/voxodeus-trait-bot",
    "techUsed": "Javascript, Node.js, Discord.js",
    },
    {
    "id":"3",
    "name": "Elephant Juice Website",
    "description":"This was created in 1st year of uiversity for the Web Development module. The site is built using HTML, CSS, JavaScript and jQuery.",
    "imageUrl":"https://i.ibb.co/NSsn8K0/Screenshot-2022-05-12-at-5-05-17-am.png",
    "gitHubLink": "https://google.com",
    "liveLink" : "https://www.google.com",
    "techUsed": "HTML, CSS, Javascript, jQuery",
    },
    {
    "id":"4",
    "name": "Portfolio Site",
    "description":"This website! This site is built in react and uses a component based building system. This website is built to demonstrate my React skills and techniques.",
    "imageUrl":"https://i.ibb.co/Kyvw02M/Screenshot-2022-05-12-at-6-54-48-am.png",
    "gitHubLink": "https://github.com/SteColeman/portfolioSite",
    "techUsed": "HTML, CSS, Javascript, React.js",
    },
    {
    "id":"5",
    "name": "Dissertation project",
    "description":"This application the the result of my dissertation module. The application is a prototype system that teaches web development inside the app with its own code editor and browser and a variable display tutorial system.",
    "imageUrl":"https://i.ibb.co/sqkJNxb/Screenshot-2022-05-12-at-5-07-05-am.png",
    "gitHubLink": "https://github.com/SteColeman/webTeachingTool",
    "techUsed": "HTML, CSS, Javascript, React.js",
    },
    {
    "id":"6",
    "name": "Currency Converter widget",
    "description":"This project has been undertaken for a module in university. the brief was simple, build a currency converter app using HTML, CSS and Vanilla JavaScript. The use of an API is forbidden to doing the exchange conversion, but is allowed to be used to get the base currency rate and complete the conversion in the widgets logic",
    "imageUrl":"https://i.ibb.co/56YKb7c/Screenshot-2022-05-12-at-6-53-17-am.png",
    "gitHubLink": "https://github.com/SteColeman/currencyConverterWidget",
    "techUsed": "HTML, CSS, Javascript, Node.js",
    },
    {
    "id":"7",
    "name": "Social media dashboard",
    "description":"A challenge completed through frontend mentor.io to demonstrate olk skills and learn new ones along the way",
    "imageUrl":"https://i.ibb.co/Wv0nvyg/Screenshot-2022-05-12-at-6-41-12-am.png",
    "gitHubLink": "https://github.com/SteColeman/social-media-dashboard",
    "techUsed": "HTML, CSS, Javascript",
    },
    {
    "id":"8",
    "name": "Four card feature",
    "description":"ProjectDescription",
    "imageUrl":"https://i.ibb.co/JCsRjTk/Screenshot-2022-05-12-at-6-49-54-am.png",
    "gitHubLink": "https://github.com/SteColeman/four-card-feature-section",
    "techUsed": "HTML, CSS, Javascript",
    }
    ];